- name: Add pgdg repo to sources.list.d
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pgdg.list
    line: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    create: true
    mode: "0644"

- name: Download PostgreSQL key and add it to system keyring
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install PostgreSQL
  ansible.builtin.apt:
    name: postgresql
    state: present

- name: Get installed PostgreSQL version # noqa: no-changed-when
  ansible.builtin.command: psql -V
  register: psql_version_output

- name: Set PostgreSQL version fact
  ansible.builtin.set_fact:
    pg_version: "{{ psql_version_output.stdout.split(' ')[2].split('.')[0] }}"

- name: Listen all IP adresses
  ansible.builtin.lineinfile:
    path: "/etc/postgresql/{{ pg_version }}/main/postgresql.conf"
    regexp: '^#?listen_addresses ='
    line: "listen_addresses = '*'"
  notify:
    - Restart PostgreSQL

- name: Listen 5432 port
  ansible.builtin.lineinfile:
    path: "/etc/postgresql/{{ pg_version }}/main/postgresql.conf"
    regexp: '^#?port ='
    line: "port = 5432"
  notify:
    - Restart PostgreSQL

- name: Add access rule to pg_hba.conf
  ansible.builtin.lineinfile:
    path: "/etc/postgresql/{{ pg_version }}/main/pg_hba.conf"
    line: "host    all             all             0.0.0.0/0               md5"
    state: present
    insertafter: EOF
  notify:
    - Restart PostgreSQL

- name: Add access rule to pg_hba.conf
  ansible.builtin.lineinfile:
    path: "/etc/postgresql/{{ pg_version }}/main/pg_hba.conf"
    line: "local   all             all                                     md5"
    state: present
    insertafter: EOF
  notify:
    - Restart PostgreSQL

- name: Add access rule to pg_hba.conf
  ansible.builtin.lineinfile:
    path: "/etc/postgresql/{{ pg_version }}/main/pg_hba.conf"
    regexp: '^local\s+all\s+all\s+peer.*$'
    line: "local   all             postgres                                     trust"
    state: present
  notify:
    - Restart PostgreSQL
