- name: Empty load_report.txt
  hosts: all
  tasks:
    - name: Ensure load_report.txt is empty before writing
      delegate_to: 127.0.0.1
      ansible.builtin.copy:
        content: ""
        dest: ../load_report.txt
        mode: "0644"
